

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components";
import { ThemeProvider } from '@mui/material/styles';
import { theme } from "@/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Habitant-Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
      <body className={inter.className}>
        
        <Header/>
        {children}
        
        </body>

      </ThemeProvider>
   
    </html>
  );
}
